package:
  name: simcem
  version: 1.0

source:
  git_url: https://github.com/toastedcrumpets/SimCem.git
  git_rev: master

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pybind11
    - cmake
    - ipopt
    - sundials
    - eigen
    - boost
    - make # [unix]
    - pkg-config # [not win]
  run:
    - python
    - ipopt
    - sundials
    

about:
  summary: A chemical engineering package
